export const ADD_FRUIT_ACTION = 'ADD_FRUIT_ACTION';
export const DELETE_FRUIT_ACTION = 'DELETE_FRUIT_ACTION';
export const FRUITS_LOADED = 'FRUITS_LOADED';
export const FRUITS_LOADED_FAILED = 'FRUITS_LOADED_FAILED';